### ISSUE TITLE
Issue resolving maven dependencies

### ISSUE THREAD

**Issue by dmarley** [mulesoft-catalyst/error-handler-plugin#1]
I was having issues resolving dependencies, so commented out the ones I was having issues with and used the following parent pom for extensions and fixed my dependencies issues

```
	<parent>
		<groupId>org.mule.extensions</groupId>
		<artifactId>mule-modules-parent</artifactId>
		<version>1.1.3</version>
	</parent>
```

I have attached a patch file for review
![error-handler-plugin__Git_](https://user-images.githubusercontent.com/134887/77664643-c5c50b00-6f3b-11ea-81b5-dc765d38d72b.png)

**Comment by biswa-mohanty** [comment]
@dmarley 
the version on the project is 1.1.5. are you having issues with 1.1.5?

**Comment by GauthierPLM** [comment]
Hello,

I also encounter many errors related to Mule' artifacts while building 4.3.0 version.
Could you provide a guide/documentation page to properly setup settings.xml/maven so the resolution works as expected on a new computer?

**Comment by gursewak96** [comment]
Hi
while deploying or issuing mvn clean install command, I am receiving this error:
Failed to execute goal on project common-error-handler: Could not resolve dependencies for project com.conflowence:common-error-handler:mule-extension:5.1.0: Could not find artifact com.mulesoft.mule.runtime.modules:mule-module-spring-config-ee:jar:4.3.0 in mulesoft-releases (https://repository.mulesoft.org/releases/) -> [Help 1]
[ERROR] 
Maven somehow not able to find the artifact
Can you please help me out ?

**Comment by biswa-mohanty** [comment]
the plugin url was incorrectly set as HTTP instead of HTTPS. that has been fixed and should not cause further problems.

**Comment by gursewak96** [comment]
I figured that out and fixed it, but I receive this error: Could not find artifact com.mulesoft.mule.runtime.modules:mule-module-spring-config-ee:jar:4.3.0 . After extensive research I found that Mule dependencies that end in '-ee' are not public. Hence mule assume once have acquired an Enterprise License and credentials for the MuleSoft Enterprise Maven customer repository and provided in the pom xml for accessing the private repository. 
Could please correct me if I wrong that to use this plugin i have to be mulesoft customer. 
According to me that jar (mule-module-spring-config-ee:jar:4.3.0) is not available for all but licensed customers.

**Comment by lssilveirads** [comment]
I am facing the same problem as my friend above. Someone managed to solve that?

**Comment by gursewak96** [comment]
> I am facing the same problem as my friend above. Someone managed to solve that?

I resolved it,

**Comment by lssilveirads** [comment]
How did you resolve it?

**Comment by BhanuAnnapoorna** [comment]
@gursewak96 How did you resolve this issue?

**Comment by gursewak96** [comment]
> How did you resolve it?

I put this inside my repositories section
`<repository>
          <id>MuleRepository</id>
          <name>MuleRepository</name>
          <url>https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/</url>
          <layout>default</layout>
          <releases>
            <enabled>true</enabled>
          </releases>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>`

**Comment by tgkumarmca** [comment]
Hi @gursewak96,

I have moved to inside the repositories section. I am still getting below error while running the deploy.sh. Could you please help me to resolve it?

com.mulesoft.mule.runtime.modules:mule-module-spring-config-ee:jar:4.3.0: Could not transfer artifact com.mulesoft.mule.runtime.modules:mule-module-spring-config-ee:pom:4.3.0 from/to MuleRepository (https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/): authorization failed for https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/com/mulesoft/mule/runtime/modules/mule-module-spring-config-ee/4.3.0/mule-module-spring-config-ee-4.3.0.pom, status: 403 Forbidden -> [Help 1]

**Comment by sf-charles** [comment]
mule-module-spring-config-ee:jar is only available from the enterprise MuleSoft respository.  This is only available to current MuleSoft customers.
