### ISSUE TITLE
unable to get it as connector under global configuration in AnyPoint Studio

### ISSUE THREAD

**Issue by dev042023** [mulesoft-catalyst/error-handler-plugin#23]
After publishing the latest error-handler-plugin-v6.0 on Exchange, it is not visible in connector configuration in global type after it is imported in AnyPoint studio. Even it is not replaced the old version which v5.0. Your response is appreciated.

**Comment by mikeconroy** [comment]
Check the Release Notes for 6.0.0 - there is no Global Configuration anymore.

**Comment by sf-charles** [comment]
As @mikeconroy stated, no global config.
