### ISSUE TITLE
Unable to build the plugin

### ISSUE THREAD

**Issue by tgkumarmca** [mulesoft-catalyst/error-handler-plugin#25]
Dear Team,

I am trying to leverage api-error-handler plug in. I am unable to build  the plugin and I am getting below error. Can someone help me to build it?

[ERROR] Failed to execute goal on project api-error-handler: Could not resolve dependencies for project a33b74fd-b990-4abb-b24b-c6ea5e0fbfc0:api-error-handler:mule-extension:6.1.0: Failed to collect dependencies at com.mulesoft.mule.runtime.modules:mule-module-spring-config-ee:jar:4.3.0: Failed to read artifact descriptor for com.mulesoft.mule.runtime.modules:mule-module-spring-config-ee:jar:4.3.0: Could not transfer artifact com.mulesoft.mule.runtime.modules:mule-module-spring-config-ee:pom:4.3.0 from/to MuleRepository (https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/): status code: 403, reason phrase: Forbidden (403) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project api-error-handler: Could not resolve dependencies for project a33b74fd-b990-4abb-b24b-c6ea5e0fbfc0:api-error-handler:mule-extension:6.1.0: Failed to collect dependencies at com.mulesoft.mule.runtime.modules:mule-module-spring-config-ee:jar:4.3.0

**Comment by F-Ayoub** [comment]
1 - Make sure that you're using this command to deploy : **mvn clean -DskipTests deploy**
2 - Make sure that the name of server in your settings.xml file is the same in the pom.xml file

**Comment by sf-charles** [comment]
You need credentials and access to MuleSoft Enterprise Repository in your settings.xml for this to work. 
 https://docs.mulesoft.com/mule-runtime/latest/maven-reference#configure-mulesoft-enterprise-repository
