### ISSUE TITLE
Error message format - is it possible to define a different one, overriding default?

### ISSUE THREAD

**Issue by rboris2000** [mulesoft-catalyst/error-handler-plugin#26]
Can I change the format of the error message?
I have requirements for much more elaborate error response,, including timestamp, correlation id, app name, failing component, etc. Does your component/plugin supports defining a different error message structure? If yes, any guidelines?
Thanks,
Boris Rovner

**Comment by sf-charles** [comment]
Addressed this by removing the previous error function and putting an example function in customErrors.dwl and README.  This feature is very situational so it must be handled in custom error dataweave.  See PR: https://github.com/mulesoft-catalyst/error-handler-plugin/pull/27

**Comment by rboris2000** [comment]
Thanks! The solution looks good. I agree that this situation should be handled in custom DataWeave.

**Comment by sf-charles** [comment]
The README discusses on how to add extra stuff to your response.  TL;DR: The error handler has a low-opinion response.  It simply maps errors to responses, which you can customize.  If you want the payload to be different or contain more information, you can throw in a transformer to modify it however you want right after the error handler.  The error handler is not going to give an opinionated response or have the feature where you can customize the response exactly for your specific needs.  The Mule way is to transform the response.
