### ISSUE TITLE
HTTP Status is always 500 when an error is handled

### ISSUE THREAD

**Issue by jbenhamou** [mulesoft-catalyst/error-handler-plugin#3]
In the alt-option branch, the http.status is set to the default value 500. [See here](https://www.evernote.com/l/AJ-50d2zYnlJSp25qZkMZ_tTO6KZvm1kGQA)

**Comment by hyperdigitalplatform** [comment]
Hi 
Any update on this? We are also facing the same problem.

Regards,

**Comment by sf-charles** [comment]
Please check against latest release in master and reopen if it exists there.  You have the flexibility to control whatever status you want.
